### ISSUE TITLE
Bill of materials (BOM)

### ISSUE THREAD

**Issue by mgoulartBR** [zjuyzj/OPL2LPT-Replica#3]
Greetings,

Is it possible to share a file listing de needed materials (TXT file) in order to build this PCB?
I tried to search it through the directories but I didn't find it.

Thanks!

**Comment by zjuyzj** [comment]
Thanks for your feedback! A Bill of Materials is appended to the README.md as a table in Markdown now with possible sources for all electronic parts (most of which from Mouser, fewer from AliExpress). PDF version of schematic and PCB are also exported for PCB building and debugging.

**Comment by mgoulartBR** [comment]
Thanks a lot!!!
